services:

  app:

    build: .
    container_name: node_app_moodmeal
    ports:
      - "3050:3000"
    volumes:
      - .:/var/www
    environment:
      - MONGO_URL=mongodb://mongo:27017/mydb
    depends_on:
      - mongo

  mongo:
    image: mongo:5.0
    container_name: mongodb_moodemeal
    ports:
      - "27520:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
